-- Create debate topics table
CREATE TABLE IF NOT EXISTS debate_topics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_id TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  difficulty TEXT CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
  category TEXT NOT NULL,
  prompt TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE debate_topics ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access to active topics
CREATE POLICY "Public can view active topics" ON debate_topics
  FOR SELECT USING (is_active = true);

-- Insert default debate topics
INSERT INTO debate_topics (topic_id, title, description, difficulty, category, prompt) VALUES
('ai-regulation', 'AI Regulation & Ethics', 'Should AI development be heavily regulated?', 'advanced', 'Technology', 'You are engaging in a debate about AI regulation and ethics. Choose a clear position and defend it passionately. DEBATE FOCUS: AI safety and control, Economic impact and job displacement, Privacy and surveillance concerns, Innovation vs. safety trade-offs, International competition and regulation. KEY ARGUMENTS TO CONSIDER: Should AI development be slowed down for safety? Who should control AI development - governments or private companies? How do we balance innovation with ethical concerns? What role should international cooperation play? DEBATE STYLE: Present clear, compelling arguments, Use specific examples and evidence, Address counterarguments proactively, Stay focused on the core issue, Respect your opponent while defending your position'),
('universal-basic-income', 'Universal Basic Income', 'Should every citizen receive a guaranteed basic income?', 'intermediate', 'Economics', 'You are debating Universal Basic Income (UBI). Take a clear position and defend it with evidence and reasoning. DEBATE FOCUS: Economic feasibility and cost, Impact on work motivation and productivity, Poverty reduction and social welfare, Automation and job displacement, Implementation challenges. KEY ARGUMENTS TO CONSIDER: Can we afford UBI without massive tax increases? Would UBI reduce or increase work motivation? How would UBI affect inflation and the economy? What about the dignity of work vs. basic security? DEBATE STYLE: Use economic data and studies when possible, Address both practical and philosophical aspects, Consider real-world pilot programs, Balance idealism with practical implementation'),
('social-media-regulation', 'Social Media Regulation', 'Should social media platforms be more heavily regulated?', 'intermediate', 'Technology', 'You are debating social media regulation. Defend your position on how much control governments should have over these platforms. DEBATE FOCUS: Free speech vs. harmful content, Mental health impacts, especially on youth, Political polarization and misinformation, Privacy and data protection, Competition and market concentration. KEY ARGUMENTS TO CONSIDER: Should platforms be responsible for user-generated content? How do we balance free speech with preventing harm? What role should government play in content moderation? Are current platforms too powerful and need breaking up? DEBATE STYLE: Use specific examples of both benefits and harms, Consider international perspectives and regulations, Address the technical challenges of content moderation, Balance individual rights with collective welfare'),
('climate-action', 'Climate Action vs. Economic Growth', 'Should we prioritize climate action over economic growth?', 'intermediate', 'Environment', 'You are debating the trade-off between climate action and economic growth. Take a position on which should be prioritized. DEBATE FOCUS: Economic costs of climate action, Long-term economic benefits of sustainability, Global cooperation and fairness, Technology and innovation solutions, Immediate vs. long-term priorities. KEY ARGUMENTS TO CONSIDER: Can we afford aggressive climate action without economic harm? What about developing countries right to grow? Are renewable energy costs worth the investment? How urgent is the climate crisis really? DEBATE STYLE: Use scientific data and economic projections, Consider both developed and developing world perspectives, Address the urgency vs. feasibility balance, Present practical solutions and alternatives'),
('remote-work', 'Remote Work vs. Office Work', 'Is remote work better than traditional office work?', 'beginner', 'Business', 'You are debating the future of work - remote vs. office. Defend your preferred work model with evidence and reasoning. DEBATE FOCUS: Productivity and performance, Work-life balance and mental health, Team collaboration and culture, Cost savings and environmental impact, Career development and networking. KEY ARGUMENTS TO CONSIDER: Are people more or less productive working remotely? How does remote work affect team dynamics and innovation? What about the social aspects and mental health? Is remote work sustainable long-term? DEBATE STYLE: Use data from recent remote work experiments, Consider different industries and job types, Address both employee and employer perspectives, Present hybrid solutions as alternatives'),
('education-reform', 'Education System Reform', 'Should we completely reform our education system?', 'intermediate', 'Education', 'You are debating education system reform. Take a position on whether our current system needs major changes. DEBATE FOCUS: Standardized testing and assessment, Curriculum relevance and job preparation, Technology integration and online learning, Teacher training and compensation, Access and equity in education. KEY ARGUMENTS TO CONSIDER: Is the current system preparing students for the future? Should we focus more on skills vs. traditional subjects? How important is standardized testing? What role should technology play in education? DEBATE STYLE: Use international comparisons and educational research, Consider different student needs and learning styles, Address both academic and practical outcomes, Present specific reform proposals'),
('healthcare-system', 'Healthcare System Reform', 'Should we move to a single-payer healthcare system?', 'advanced', 'Healthcare', 'You are debating healthcare system reform, specifically single-payer vs. private insurance models. DEBATE FOCUS: Cost and efficiency of different systems, Quality of care and patient outcomes, Access and equity in healthcare, Innovation and medical advancement, Implementation challenges and transition costs. KEY ARGUMENTS TO CONSIDER: Can single-payer provide better care at lower cost? How would it affect medical innovation and research? What about choice and competition in healthcare? Is the current system sustainable? DEBATE STYLE: Use international healthcare system comparisons, Address both economic and moral arguments, Consider practical implementation challenges, Present evidence from existing single-payer systems'),
('immigration-policy', 'Immigration Policy', 'Should we have more open or restrictive immigration policies?', 'advanced', 'Politics', 'You are debating immigration policy. Take a position on whether countries should have more open or restrictive policies. DEBATE FOCUS: Economic impact of immigration, Cultural integration and social cohesion, Security and border control, Humanitarian obligations and human rights, Labor market effects and job competition. KEY ARGUMENTS TO CONSIDER: Do immigrants help or hurt the economy? How do we balance security with humanitarian concerns? What about cultural integration and social cohesion? Should we prioritize skilled vs. family-based immigration? DEBATE STYLE: Use economic data and demographic studies, Consider both humanitarian and practical concerns, Address security and integration challenges, Present balanced policy proposals'); 